In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
l = range(1000)

%timeit [i**2 for i in l]

298 μs ± 29.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
import numpy as np

a = np.arange(1000)

%timeit a**2

4.14 μs ± 327 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Creating Arrays

In [5]:
a = np.array([1,2,3,4])  # one dimension array
print(a.ndim)

1


In [2]:
import numpy as np

b = np.array([[1,2,3],[4,5,6]])
print(b.ndim)

2


In [2]:
import numpy as np

c = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

print(c.ndim)
print(c)

3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a.shape)

(4,)


In [6]:
import numpy as np

b = np.array([[1,2,3],
              [4,5,6]])
print(b.shape)

(2, 3)


In [7]:
import numpy as np

c = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(c.shape)

(2, 2, 2)


# Functions For Creating Array

In [8]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [10]:
# using linspace
a = np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [11]:
a = np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [12]:
a = np.linspace(0,1,4)
print(a)

[0.         0.33333333 0.66666667 1.        ]


In [13]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
import numpy as np

a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
import numpy as np

a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [24]:
print(np.diag(a))


[1 2 3 4]


# Basic Data Types

In [25]:
a = np.arange(10)
print(a.dtype)
print(a)

int64
[0 1 2 3 4 5 6 7 8 9]


In [26]:
a = np.arange(10,dtype="float64")
print(a.dtype)
print(a)

float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# Other Data Type

In [28]:
import numpy as np

a = np.array([1+2j, 2+4j])
print(a.dtype)
print(a)

complex128
[1.+2.j 2.+4.j]


In [29]:
a = np.array(['Pavan','Mani'])
print(a.dtype) # unicode string type

<U5


In [30]:
a = np.array([True,False])
print(a.dtype)

bool


# Indexing And Slicing

In [31]:
a = np.arange(10)
print(a[5])

5


In [33]:
import numpy as np

a = np.arange(2, 20, 2)
print(a[2])

6


In [34]:
a = np.diag([1,2,3])
print(a[2,2])

3


In [37]:
a = [2, 1]
print(a)

[2, 1]


# Slicing : used to acess  elements

In [38]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
print(a[1:8:2])


[1 3 5 7]


# Copies And Viewing

In [40]:
a = np.arange(10)
b = a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [41]:
print(np.shares_memory(a,b))

True


In [42]:
b[0] = 10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [43]:
a = np.arange(10)
b = a[::2].copy()  # force a copy
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [44]:
print(np.shares_memory(a,b))

False


In [45]:
b[0] = 10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


# Random Number Generator

In [46]:
a = np.random.randint(0,2,15)
print(a)

[0 0 0 0 1 1 1 0 0 1 1 1 0 1 0]


In [47]:
a = np.random.randint(0,9,6)
print(a)

[4 1 1 8 0 8]


In [48]:
a = np.random.randint(0,9,6)
print(a)

[5 0 6 0 2 0]


# Element Wise Operations

In [49]:
a = np.array([1,2,3,4])
print(a+1)  # add + 1

[2 3 4 5]


In [50]:
print(a**2) # Squares


[ 1  4  9 16]


# All Arithmetic Operates ElementWise

In [51]:
b = np.ones(4) + 1 #[2 2 2 2]
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [2. 2. 2. 2.]


In [52]:
print(a*b)

[2. 4. 6. 8.]


In [53]:
print(a-b)

[-1.  0.  1.  2.]


In [54]:
l = np.array([1,2,3,4])
l2 = np.array([1,2,3,4])
print(l*l2)

[ 1  4  9 16]


# Comparison Operators

In [55]:
a = np.array([1,2,3,4])
b = np.array([5,2,7,4])
print(a==b)

[False  True False  True]


In [56]:
print(a<b)

[ True False  True False]


In [57]:
print(a>b)

[False False False False]


# Array Wise Comparision

In [58]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [59]:
print(np.array_equal(a,c))

True


# Logical Operators

In [60]:
a = np.array([1,0,1,0],dtype = 'bool')
b = np.array([1,1,0,0],dtype = 'bool')
print(np.logical_or(a,b))

[ True  True  True False]


In [61]:
print(np.logical_and(a,b))

[ True False False False]


# Trigonmetry / Transcendental Functions

In [62]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [63]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [64]:
np.log(a)

C:\Users\defaultuser0\AppData\Local\Temp\ipykernel_13868\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [65]:
print(np.exp(a))

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [66]:
print(np.cos(a))

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [67]:
print(np.tan(a))

[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128]


# Basic Reductions


In [70]:
x = np.array([1,2,3,4])
print(np.sum(x))

10


In [72]:
x = np.array([[1,2],[1,2]])
print(x)

[[1 2]
 [1 2]]


In [73]:
x.sum(axis=0)  # column dimensions

array([2, 4])

In [74]:
x.sum(axis=1)  # row dimension

array([3, 3])

# Other Reduction

In [75]:
x = np.array([1,2,3,4])
print(x.min())

1


In [76]:
print(x.max())

4


In [77]:
print(x.argmin())

0


In [ ]:
z